name: Deploy to Firebase

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        type: choice
        options:
          - dev
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@v3

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build Vite app
      - name: Build Vite app
        run: npm run build

      # Deploy DEV
      - name: Deploy to Dev
        if: github.event.inputs.environment == 'dev'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_DEV }}"
          projectId: weather-app-dev-a6aa7
          entryPoint: .  
          channelId: live

      # Deploy PROD
      - name: Deploy to Prod
        if: github.event.inputs.environment == 'prod'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROD }}"
          projectId: weather-app-prod-530a8
          entryPoint: .
          channelId: live
